In [398]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [399]:
df=pd.read_csv('bank_transactions_data_2.csv')
df.head()

,TransactionID,AccountID,TransactionAmount,TransactionDate,TransactionType,Location,DeviceID,IP Address,MerchantID,Channel,CustomerAge,CustomerOccupation,TransactionDuration,LoginAttempts,AccountBalance,PreviousTransactionDate
0,TX000001,AC00128,14.09,2023-04-11 16:29:14,Debit,San Diego,D000380,162.198.218.92,M015,ATM,70,Doctor,81,1,5112.21,2024-11-04 08:08:08
1,TX000002,AC00455,376.24,2023-06-27 16:44:19,Debit,Houston,D000051,13.149.61.4,M052,ATM,68,Doctor,141,1,13758.91,2024-11-04 08:09:35
2,TX000003,AC00019,126.29,2023-07-10 18:16:08,Debit,Mesa,D000235,215.97.143.157,M009,Online,19,Student,56,1,1122.35,2024-11-04 08:07:04
3,TX000004,AC00070,184.50,2023-05-05 16:32:11,Debit,Raleigh,D000187,200.13.225.150,M002,Online,26,Student,25,1,8569.06,2024-11-04 08:09:06
4,TX000005,AC00411,13.45,2023-10-16 17:51:24,Credit,Atlanta,D000308,65.164.3.100,M091,Online,26,Student,198,1,7429.40,2024-11-04 08:06:39


In [400]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2512 entries, 0 to 2511
Data columns (total 16 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   TransactionID            2512 non-null   object 
 1   AccountID                2512 non-null   object 
 2   TransactionAmount        2512 non-null   float64
 3   TransactionDate          2512 non-null   object 
 4   TransactionType          2512 non-null   object 
 5   Location                 2512 non-null   object 
 6   DeviceID                 2512 non-null   object 
 7   IP Address               2512 non-null   object 
 8   MerchantID               2512 non-null   object 
 9   Channel                  2512 non-null   object 
 10  CustomerAge              2512 non-null   int64  
 11  CustomerOccupation       2512 non-null   object 
 12  TransactionDuration      2512 non-null   int64  
 13  LoginAttempts            2512 non-null   int64  
 14  AccountBalance          

In [401]:
df.describe()

,TransactionAmount,CustomerAge,TransactionDuration,LoginAttempts,AccountBalance
count,2512.000000,2512.000000,2512.000000,2512.000000,2512.000000
mean,297.593778,44.673965,119.643312,1.124602,5114.302966
std,291.946243,17.792198,69.963757,0.602662,3900.942499
min,0.260000,18.000000,10.000000,1.000000,101.250000
25%,81.885000,27.000000,63.000000,1.000000,1504.370000
50%,211.140000,45.000000,112.500000,1.000000,4735.510000
75%,414.527500,59.000000,161.000000,1.000000,7678.820000
max,1919.110000,80.000000,300.000000,5.000000,14977.990000


In [402]:
df.shape

(2512, 16)

In [403]:
df_copy=df.copy()

In [404]:
df_copy['TransactionID'].unique

<bound method Series.unique of 0       TX000001
1       TX000002
2       TX000003
3       TX000004
4       TX000005
          ...   
2507    TX002508
2508    TX002509
2509    TX002510
2510    TX002511
2511    TX002512
Name: TransactionID, Length: 2512, dtype: object>

In [405]:
df_copy.isnull().sum()

TransactionID              0
AccountID                  0
TransactionAmount          0
TransactionDate            0
TransactionType            0
Location                   0
DeviceID                   0
IP Address                 0
MerchantID                 0
Channel                    0
CustomerAge                0
CustomerOccupation         0
TransactionDuration        0
LoginAttempts              0
AccountBalance             0
PreviousTransactionDate    0
dtype: int64

## Conclusion 
All the tranction ID are different.so there is no duplicate is present.

In [406]:
df['TransactionDate'].unique()

array(['2023-04-11 16:29:14', '2023-06-27 16:44:19',
       '2023-07-10 18:16:08', ..., '2023-08-21 17:08:50',
       '2023-02-24 16:24:46', '2023-02-14 16:21:23'],
      shape=(2512,), dtype=object)

In [407]:
df_copy['TransactionDate']=pd.to_datetime(df_copy['TransactionDate'])
df_copy['Date']=df_copy['TransactionDate'].dt.day
df_copy['Month']=df_copy['TransactionDate'].dt.month
df_copy['Year']=df_copy['TransactionDate'].dt.year
df_copy['Hours']=df_copy['TransactionDate'].dt.hour
df_copy['minutes']=df_copy['TransactionDate'].dt.minute
df_copy['seconds']=df_copy['TransactionDate'].dt.second
df_copy.head()

,TransactionID,AccountID,TransactionAmount,TransactionDate,TransactionType,Location,DeviceID,IP Address,MerchantID,Channel,...,TransactionDuration,LoginAttempts,AccountBalance,PreviousTransactionDate,Date,Month,Year,Hours,minutes,seconds
0,TX000001,AC00128,14.09,2023-04-11 16:29:14,Debit,San Diego,D000380,162.198.218.92,M015,ATM,...,81,1,5112.21,2024-11-04 08:08:08,11,4,2023,16,29,14
1,TX000002,AC00455,376.24,2023-06-27 16:44:19,Debit,Houston,D000051,13.149.61.4,M052,ATM,...,141,1,13758.91,2024-11-04 08:09:35,27,6,2023,16,44,19
2,TX000003,AC00019,126.29,2023-07-10 18:16:08,Debit,Mesa,D000235,215.97.143.157,M009,Online,...,56,1,1122.35,2024-11-04 08:07:04,10,7,2023,18,16,8
3,TX000004,AC00070,184.50,2023-05-05 16:32:11,Debit,Raleigh,D000187,200.13.225.150,M002,Online,...,25,1,8569.06,2024-11-04 08:09:06,5,5,2023,16,32,11
4,TX000005,AC00411,13.45,2023-10-16 17:51:24,Credit,Atlanta,D000308,65.164.3.100,M091,Online,...,198,1,7429.40,2024-11-04 08:06:39,16,10,2023,17,51,24


In [408]:
df_copy['Year'].unique()

array([2023, 2024], dtype=int32)

## conclusion 
The whole data is of only 2 years.Machine learning model understands the numbers no nedd to convert it in any form.

In [409]:
## now we should drop the Transction Date column it is of no sense 
df_copy.drop(axis=1,inplace=True,columns='TransactionDate')

In [410]:
df_copy.head()

,TransactionID,AccountID,TransactionAmount,TransactionType,Location,DeviceID,IP Address,MerchantID,Channel,CustomerAge,...,TransactionDuration,LoginAttempts,AccountBalance,PreviousTransactionDate,Date,Month,Year,Hours,minutes,seconds
0,TX000001,AC00128,14.09,Debit,San Diego,D000380,162.198.218.92,M015,ATM,70,...,81,1,5112.21,2024-11-04 08:08:08,11,4,2023,16,29,14
1,TX000002,AC00455,376.24,Debit,Houston,D000051,13.149.61.4,M052,ATM,68,...,141,1,13758.91,2024-11-04 08:09:35,27,6,2023,16,44,19
2,TX000003,AC00019,126.29,Debit,Mesa,D000235,215.97.143.157,M009,Online,19,...,56,1,1122.35,2024-11-04 08:07:04,10,7,2023,18,16,8
3,TX000004,AC00070,184.50,Debit,Raleigh,D000187,200.13.225.150,M002,Online,26,...,25,1,8569.06,2024-11-04 08:09:06,5,5,2023,16,32,11
4,TX000005,AC00411,13.45,Credit,Atlanta,D000308,65.164.3.100,M091,Online,26,...,198,1,7429.40,2024-11-04 08:06:39,16,10,2023,17,51,24


In [411]:
df_copy['TransactionType'].unique()

array(['Debit', 'Credit'], dtype=object)

In [412]:
## Mapping of "Debit":0 and "Credit":1
df_copy['TransactionType']=df_copy['TransactionType'].map({'Debit':0,'Credit':1})
df.head()

,TransactionID,AccountID,TransactionAmount,TransactionDate,TransactionType,Location,DeviceID,IP Address,MerchantID,Channel,CustomerAge,CustomerOccupation,TransactionDuration,LoginAttempts,AccountBalance,PreviousTransactionDate
0,TX000001,AC00128,14.09,2023-04-11 16:29:14,Debit,San Diego,D000380,162.198.218.92,M015,ATM,70,Doctor,81,1,5112.21,2024-11-04 08:08:08
1,TX000002,AC00455,376.24,2023-06-27 16:44:19,Debit,Houston,D000051,13.149.61.4,M052,ATM,68,Doctor,141,1,13758.91,2024-11-04 08:09:35
2,TX000003,AC00019,126.29,2023-07-10 18:16:08,Debit,Mesa,D000235,215.97.143.157,M009,Online,19,Student,56,1,1122.35,2024-11-04 08:07:04
3,TX000004,AC00070,184.50,2023-05-05 16:32:11,Debit,Raleigh,D000187,200.13.225.150,M002,Online,26,Student,25,1,8569.06,2024-11-04 08:09:06
4,TX000005,AC00411,13.45,2023-10-16 17:51:24,Credit,Atlanta,D000308,65.164.3.100,M091,Online,26,Student,198,1,7429.40,2024-11-04 08:06:39


In [413]:
df_copy['TransactionType'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 2512 entries, 0 to 2511
Series name: TransactionType
Non-Null Count  Dtype
--------------  -----
2512 non-null   int64
dtypes: int64(1)
memory usage: 19.8 KB


In [414]:
df_copy['Location'].unique()

array(['San Diego', 'Houston', 'Mesa', 'Raleigh', 'Atlanta',
       'Oklahoma City', 'Seattle', 'Indianapolis', 'Detroit', 'Nashville',
       'Albuquerque', 'Memphis', 'Louisville', 'Denver', 'Austin',
       'Columbus', 'Los Angeles', 'Las Vegas', 'Fort Worth', 'Miami',
       'Milwaukee', 'Baltimore', 'New York', 'San Francisco', 'San Jose',
       'San Antonio', 'Philadelphia', 'Charlotte', 'Tucson', 'Chicago',
       'Sacramento', 'Kansas City', 'Omaha', 'Virginia Beach', 'Dallas',
       'Boston', 'Jacksonville', 'Phoenix', 'Washington', 'El Paso',
       'Colorado Springs', 'Fresno', 'Portland'], dtype=object)

In [415]:
df_copy['Channel'].unique()

array(['ATM', 'Online', 'Branch'], dtype=object)

In [416]:
## apply encoder to the location
from sklearn.preprocessing import OneHotEncoder
encoder=OneHotEncoder()


In [417]:
encoder.fit_transform(df_copy[['Location']]).toarray()

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], shape=(2512, 43))

In [418]:
new_df=pd.DataFrame(encoder.fit_transform(df_copy[['Location']]).toarray(),columns=encoder.get_feature_names_out())

In [419]:
new_df.head()


,Location_Albuquerque,Location_Atlanta,Location_Austin,Location_Baltimore,Location_Boston,Location_Charlotte,Location_Chicago,Location_Colorado Springs,Location_Columbus,Location_Dallas,...,Location_Raleigh,Location_Sacramento,Location_San Antonio,Location_San Diego,Location_San Francisco,Location_San Jose,Location_Seattle,Location_Tucson,Location_Virginia Beach,Location_Washington
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0


In [420]:
df_copy = pd.concat([df_copy, new_df], axis=1)
df_copy.head()

,TransactionID,AccountID,TransactionAmount,TransactionType,Location,DeviceID,IP Address,MerchantID,Channel,CustomerAge,...,Location_Raleigh,Location_Sacramento,Location_San Antonio,Location_San Diego,Location_San Francisco,Location_San Jose,Location_Seattle,Location_Tucson,Location_Virginia Beach,Location_Washington
0,TX000001,AC00128,14.09,0,San Diego,D000380,162.198.218.92,M015,ATM,70,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
1,TX000002,AC00455,376.24,0,Houston,D000051,13.149.61.4,M052,ATM,68,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,TX000003,AC00019,126.29,0,Mesa,D000235,215.97.143.157,M009,Online,19,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,TX000004,AC00070,184.50,0,Raleigh,D000187,200.13.225.150,M002,Online,26,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,TX000005,AC00411,13.45,1,Atlanta,D000308,65.164.3.100,M091,Online,26,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0


In [421]:
df.shape

(2512, 16)

In [422]:
## now location is of no use so we can drop it 
df_copy.drop(axis=1,columns='Location',inplace=True)
df_copy.head()

,TransactionID,AccountID,TransactionAmount,TransactionType,DeviceID,IP Address,MerchantID,Channel,CustomerAge,CustomerOccupation,...,Location_Raleigh,Location_Sacramento,Location_San Antonio,Location_San Diego,Location_San Francisco,Location_San Jose,Location_Seattle,Location_Tucson,Location_Virginia Beach,Location_Washington
0,TX000001,AC00128,14.09,0,D000380,162.198.218.92,M015,ATM,70,Doctor,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
1,TX000002,AC00455,376.24,0,D000051,13.149.61.4,M052,ATM,68,Doctor,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,TX000003,AC00019,126.29,0,D000235,215.97.143.157,M009,Online,19,Student,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,TX000004,AC00070,184.50,0,D000187,200.13.225.150,M002,Online,26,Student,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,TX000005,AC00411,13.45,1,D000308,65.164.3.100,M091,Online,26,Student,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0


In [423]:
df_copy.shape

(2512, 63)

In [424]:
df_copy['CustomerOccupation'].unique()

array(['Doctor', 'Student', 'Retired', 'Engineer'], dtype=object)

In [425]:
## apply encoder to the Occupation
from sklearn.preprocessing import OneHotEncoder
encoder=OneHotEncoder()


In [426]:
encoder.fit_transform(df_copy[['CustomerOccupation']]).toarray()

array([[1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 1.],
       ...,
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.]], shape=(2512, 4))

In [427]:
new_CostOpp_df=pd.DataFrame(encoder.fit_transform(df_copy[['CustomerOccupation']]).toarray(),columns=encoder.get_feature_names_out())

In [428]:
df_copy = pd.concat([df_copy, new_CostOpp_df], axis=1)
df_copy.head()

,TransactionID,AccountID,TransactionAmount,TransactionType,DeviceID,IP Address,MerchantID,Channel,CustomerAge,CustomerOccupation,...,Location_San Francisco,Location_San Jose,Location_Seattle,Location_Tucson,Location_Virginia Beach,Location_Washington,CustomerOccupation_Doctor,CustomerOccupation_Engineer,CustomerOccupation_Retired,CustomerOccupation_Student
0,TX000001,AC00128,14.09,0,D000380,162.198.218.92,M015,ATM,70,Doctor,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
1,TX000002,AC00455,376.24,0,D000051,13.149.61.4,M052,ATM,68,Doctor,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
2,TX000003,AC00019,126.29,0,D000235,215.97.143.157,M009,Online,19,Student,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
3,TX000004,AC00070,184.50,0,D000187,200.13.225.150,M002,Online,26,Student,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
4,TX000005,AC00411,13.45,1,D000308,65.164.3.100,M091,Online,26,Student,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0


In [429]:
df_copy.drop(axis=1,columns='CustomerOccupation',inplace=True)


In [430]:
df_copy.head()

,TransactionID,AccountID,TransactionAmount,TransactionType,DeviceID,IP Address,MerchantID,Channel,CustomerAge,TransactionDuration,...,Location_San Francisco,Location_San Jose,Location_Seattle,Location_Tucson,Location_Virginia Beach,Location_Washington,CustomerOccupation_Doctor,CustomerOccupation_Engineer,CustomerOccupation_Retired,CustomerOccupation_Student
0,TX000001,AC00128,14.09,0,D000380,162.198.218.92,M015,ATM,70,81,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
1,TX000002,AC00455,376.24,0,D000051,13.149.61.4,M052,ATM,68,141,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
2,TX000003,AC00019,126.29,0,D000235,215.97.143.157,M009,Online,19,56,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
3,TX000004,AC00070,184.50,0,D000187,200.13.225.150,M002,Online,26,25,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
4,TX000005,AC00411,13.45,1,D000308,65.164.3.100,M091,Online,26,198,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0


In [431]:
encoder.fit_transform(df_copy[['Channel']]).toarray()


array([[1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       ...,
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.]], shape=(2512, 3))

In [432]:
new_Channel_df=pd.DataFrame(encoder.fit_transform(df_copy[['Channel']]).toarray(),columns=encoder.get_feature_names_out())

In [433]:
df_copy = pd.concat([df_copy, new_Channel_df], axis=1)
df_copy.head()

,TransactionID,AccountID,TransactionAmount,TransactionType,DeviceID,IP Address,MerchantID,Channel,CustomerAge,TransactionDuration,...,Location_Tucson,Location_Virginia Beach,Location_Washington,CustomerOccupation_Doctor,CustomerOccupation_Engineer,CustomerOccupation_Retired,CustomerOccupation_Student,Channel_ATM,Channel_Branch,Channel_Online
0,TX000001,AC00128,14.09,0,D000380,162.198.218.92,M015,ATM,70,81,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0
1,TX000002,AC00455,376.24,0,D000051,13.149.61.4,M052,ATM,68,141,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0
2,TX000003,AC00019,126.29,0,D000235,215.97.143.157,M009,Online,19,56,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
3,TX000004,AC00070,184.50,0,D000187,200.13.225.150,M002,Online,26,25,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
4,TX000005,AC00411,13.45,1,D000308,65.164.3.100,M091,Online,26,198,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0


In [434]:
df_copy.drop(axis=1,columns='Channel',inplace=True)

In [435]:
df_copy.head()

,TransactionID,AccountID,TransactionAmount,TransactionType,DeviceID,IP Address,MerchantID,CustomerAge,TransactionDuration,LoginAttempts,...,Location_Tucson,Location_Virginia Beach,Location_Washington,CustomerOccupation_Doctor,CustomerOccupation_Engineer,CustomerOccupation_Retired,CustomerOccupation_Student,Channel_ATM,Channel_Branch,Channel_Online
0,TX000001,AC00128,14.09,0,D000380,162.198.218.92,M015,70,81,1,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0
1,TX000002,AC00455,376.24,0,D000051,13.149.61.4,M052,68,141,1,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0
2,TX000003,AC00019,126.29,0,D000235,215.97.143.157,M009,19,56,1,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
3,TX000004,AC00070,184.50,0,D000187,200.13.225.150,M002,26,25,1,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
4,TX000005,AC00411,13.45,1,D000308,65.164.3.100,M091,26,198,1,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0


In [436]:
df_copy.shape

(2512, 68)

In [437]:
df_copy.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2512 entries, 0 to 2511
Data columns (total 68 columns):
 #   Column                       Non-Null Count  Dtype  
---  ------                       --------------  -----  
 0   TransactionID                2512 non-null   object 
 1   AccountID                    2512 non-null   object 
 2   TransactionAmount            2512 non-null   float64
 3   TransactionType              2512 non-null   int64  
 4   DeviceID                     2512 non-null   object 
 5   IP Address                   2512 non-null   object 
 6   MerchantID                   2512 non-null   object 
 7   CustomerAge                  2512 non-null   int64  
 8   TransactionDuration          2512 non-null   int64  
 9   LoginAttempts                2512 non-null   int64  
 10  AccountBalance               2512 non-null   float64
 11  PreviousTransactionDate      2512 non-null   object 
 12  Date                         2512 non-null   int32  
 13  Month             

In [438]:
df_copy['PreviousTransactionDate']=pd.to_datetime(df_copy['PreviousTransactionDate'])
df_copy['Prev_Date']=df_copy['PreviousTransactionDate'].dt.day
df_copy['prev_Month']=df_copy['PreviousTransactionDate'].dt.month
df_copy['prev_Year']=df_copy['PreviousTransactionDate'].dt.year
df_copy['prev_Hours']=df_copy['PreviousTransactionDate'].dt.hour
df_copy['prev_minutes']=df_copy['PreviousTransactionDate'].dt.minute
df_copy['prev_seconds']=df_copy['PreviousTransactionDate'].dt.second

In [439]:
df_copy.head()

,TransactionID,AccountID,TransactionAmount,TransactionType,DeviceID,IP Address,MerchantID,CustomerAge,TransactionDuration,LoginAttempts,...,CustomerOccupation_Student,Channel_ATM,Channel_Branch,Channel_Online,Prev_Date,prev_Month,prev_Year,prev_Hours,prev_minutes,prev_seconds
0,TX000001,AC00128,14.09,0,D000380,162.198.218.92,M015,70,81,1,...,0.0,1.0,0.0,0.0,4,11,2024,8,8,8
1,TX000002,AC00455,376.24,0,D000051,13.149.61.4,M052,68,141,1,...,0.0,1.0,0.0,0.0,4,11,2024,8,9,35
2,TX000003,AC00019,126.29,0,D000235,215.97.143.157,M009,19,56,1,...,1.0,0.0,0.0,1.0,4,11,2024,8,7,4
3,TX000004,AC00070,184.50,0,D000187,200.13.225.150,M002,26,25,1,...,1.0,0.0,0.0,1.0,4,11,2024,8,9,6
4,TX000005,AC00411,13.45,1,D000308,65.164.3.100,M091,26,198,1,...,1.0,0.0,0.0,1.0,4,11,2024,8,6,39


In [440]:
df_copy.shape

(2512, 74)

In [441]:
df_copy.to_csv('data/Bank_transaction_cleaned.csv')