In [1]:
!pip install numpy


   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.1/5.1 MB 428.9 kB/s  0:00:11m0:00:0100:01


In [3]:
import numpy as np 

arr1=np.array([1,2,4])
print(arr1)
print(type(arr1))
print(arr1.shape)


[1 2 4]
<class 'numpy.ndarray'>
(3,)


In [5]:
arr2=np.array([1,2,3,4,5])
arr2.reshape(1,5) ## one row 5 colouns


array([[1, 2, 3, 4, 5]])

In [7]:
arr2=np.array([[1,2,3,4]])
arr2.shape

(1, 4)

In [9]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [12]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [13]:
## identity matrix 
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [14]:
## Numpy vecterized operation
arr1=np.array([1,2,3,4,5])
arr2=np.array([10,20,30,40,50])

## Element wise addition
print("Addition",arr1+arr2)
print("Substraction", arr1-arr2)
print("multiplication",arr1*arr2)
print("Division",arr1/arr2)

Addition [11 22 33 44 55]
Substraction [ -9 -18 -27 -36 -45]
multiplication [ 10  40  90 160 250]
Division [0.1 0.1 0.1 0.1 0.1]


In [15]:
## universal function
arr=np.array([2,3,4,5,6])
## square root
print(np.sqrt(arr))

## Exponential
print(np.exp(arr))

## sine()
print(np.sin(arr))

print(np.log(arr))

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [29]:
## array silicing and indexing 

arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("Array: \n",arr)
print(arr[0][2])
print(arr[0:2, 2:])
print(arr[1:,1:3])

Array: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
3
[[3 4]
 [7 8]]
[[ 6  7]
 [10 11]]


In [30]:
## modify arr elemnt 
arr[0,0]=100
print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [31]:
arr[1:]=100
print(arr)

[[100   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]


In [32]:
## statistical concept -- Normalization
data=np.array([1,2,3,4,5])

mean=np.mean(data)
std_dev=np.std(data)

normalized_data=(data-mean)/std_dev
print("Normalized data: ",normalized_data)

Normalized data:  [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [33]:
## logical operation
data=np.array([1,2,3,4,5,6,7])
data[data>=5]

array([5, 6, 7])