# Module: NumPy Assignments
## Lesson: NumPy
### Assignment 1: Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

### Assignment 2: Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.
2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

### Assignment 3: Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

### Assignment 4: Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.
2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

### Assignment 5: Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.
2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

### Assignment 6: Linear Algebra

1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.
2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

### Assignment 7: Advanced Array Manipulation

1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).
2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).

### Assignment 8: Fancy Indexing and Boolean Indexing

1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.
2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.

### Assignment 9: Structured Arrays

1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.
2. Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.

### Assignment 10: Masked Arrays

1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.
2. Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. Replace the masked elements with the mean of the unmasked elements.

In [2]:
## Assignmnent 1

# 1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the 
# third column with 1.
# 2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

import numpy as np

# Create 5x5 array with random integers between 1 and 20
d = np.random.randint(1, 20, size=(5, 5))

# Replace 3rd column (index 2) with 1
d[:, 2] = 1

print(d)

[[ 9 17  1 13  8]
 [17  3  1 16  6]
 [10 17  1 14 19]
 [12  4  1 10 18]
 [13  4  1  6 12]]


In [ ]:
# 2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

c=np.arange(1,17).reshape((4,4))
# for i in range (0,4):
#     for j in range(0,4):
#         if(i==j):
#             c[i][j]=0

np.fill_diagonal(c,0)
print(c)

[[ 0  2  3  4]
 [ 5  0  7  8]
 [ 9 10  0 12]
 [13 14 15  0]]


In [38]:
### Assignment 2: Array Indexing and Slicing

# 1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th 
# rows and 2nd to 4th columns.
# 2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

array=np.arange(1,37).reshape(6,6)
print(array)
d=np.array(array[2:5,1:5])
print(d)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]
[[14 15 16 17]
 [20 21 22 23]
 [26 27 28 29]]


In [ ]:
### Assignment 3: Array Operations

# 1. Create two NumPy arrays of shape (3, 4) filled with random integers. 
# Perform element-wise addition, subtraction, multiplication, and division.
# 2. Create a NumPy array of shape (4, 4) with values from 1 to 16. 
# Compute the row-wise and column-wise sum.

arr2=np.random.randint(1,20,size=(3,4))
print(arr2)
arr3=np.random.randint(1,40,size=(3,4))
print(arr3)

sum=arr3+arr2
print("sum is:",sum)

diff=arr3-arr2
print("diff is:",diff)

mul=arr2*arr3
print("MUltiplication is:",mul)

div=arr2/arr3
print("Division is:",div)




[[19 15 17  6]
 [ 9 10 17 15]
 [ 3  5 18 14]]
[[ 1 18 23  1]
 [28 16 38 17]
 [26 35 30 37]]
sum is: [[20 33 40  7]
 [37 26 55 32]
 [29 40 48 51]]
diff is: [[-18   3   6  -5]
 [ 19   6  21   2]
 [ 23  30  12  23]]
MUltiplication is: [[ 19 270 391   6]
 [252 160 646 255]
 [ 78 175 540 518]]
Division is: [[19.          0.83333333  0.73913043  6.        ]
 [ 0.32142857  0.625       0.44736842  0.88235294]
 [ 0.11538462  0.14285714  0.6         0.37837838]]


In [18]:
##Question 2
arr4=np.random.randint(1,17,size=(4,4))
print(arr4)
# for i in range(0,4):
#     sum=0
#     for j in range(0,4):
#         sum=sum+arr4[j]

# print("column wise sum is:",sum)

print("column wise sum is:",np.sum(arr4,axis=0))

print("row wise sum is:",np.sum(arr4,axis=1))


[[ 6  1  2 11]
 [14 12 14  3]
 [ 5 12  5 12]
 [16  9  2  9]]
column wise sum is: [41 34 23 35]
row wise sum is: [20 43 34 36]
