In [4]:
!pip install tensorflow

ERROR: Could not find a version that satisfies the requirement tensorflow==2.0.0-rc0 (from versions: 2.20.0rc0, 2.20.0, 2.21.0rc0, 2.21.0rc1, 2.21.0)
ERROR: No matching distribution found for tensorflow==2.0.0-rc0


In [5]:
!pip install tensorflow-gpu

  Using cached tensorflow-gpu-2.12.0.tar.gz (2.6 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [77 lines of output]
      Traceback (most recent call last):
        File "/private/var/folders/yb/1vxfk8_x2fbdnqhyn4mynsnr0000gn/T/pip-build-env-uwtsfv0g/overlay/lib/python3.13/site-packages/setuptools/_vendor/packaging/requirements.py", line 36, in __init__
          parsed = _parse_requirement(requirement_string)
        File "/private/var/folders/yb/1vxfk8_x2fbdnqhyn4mynsnr0000gn/T/pip-build-env-uwtsfv0g/overlay/lib/python3.13/site-packages/setuptools/_vendor/packaging/_parser.py", line 71, in parse_requirement
          return _parse_requirement(Tokenizer(source, rules=DEFAULT_RULES))
        File "/private/var/folders/yb/1vxfk8_x2fbdnqhyn4mynsnr0000gn/T/pip-build-env-uwtsfv0g/overlay/lib/python3.13/site-packages

In [7]:
import tensorflow as tf 
from tensorflow import keras 
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Flatten,Dense

In [8]:
print(tf.__version__)

2.21.0


In [9]:
import numpy as np
import pandas as pd 
from sklearn.model_selection import train_test_split

In [10]:
dataset = pd.read_csv('Churn_Modelling.csv')

In [11]:
dataset.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0


In [12]:
X= dataset.drop(labels=['CustomerId','Surname','RowNumber','Exited'],axis=1)
y=dataset['Exited']

In [13]:
X.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,619,France,Female,42,2,0.00,1,1,1,101348.88
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58
2,502,France,Female,42,8,159660.80,3,1,0,113931.57
3,699,France,Female,39,1,0.00,2,0,0,93826.63
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10


In [14]:
y.head()

0    1
1    0
2    1
3    0
4    0
Name: Exited, dtype: int64

In [15]:
from sklearn.preprocessing import LabelEncoder

In [16]:
label1=LabelEncoder()
X['Geography']=label1.fit_transform(X['Geography'])

In [17]:
X.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,619,0,Female,42,2,0.00,1,1,1,101348.88
1,608,2,Female,41,1,83807.86,1,0,1,112542.58
2,502,0,Female,42,8,159660.80,3,1,0,113931.57
3,699,0,Female,39,1,0.00,2,0,0,93826.63
4,850,2,Female,43,2,125510.82,1,1,1,79084.10


In [18]:
label=LabelEncoder()
X['Gender']=label.fit_transform(X['Gender'])
X.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,619,0,0,42,2,0.00,1,1,1,101348.88
1,608,2,0,41,1,83807.86,1,0,1,112542.58
2,502,0,0,42,8,159660.80,3,1,0,113931.57
3,699,0,0,39,1,0.00,2,0,0,93826.63
4,850,2,0,43,2,125510.82,1,1,1,79084.10


In [20]:
X = pd.get_dummies(X, drop_first=True, columns=['Geography'])
X.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_1,Geography_2
0,619,0,42,2,0.00,1,1,1,101348.88,False,False
1,608,0,41,1,83807.86,1,0,1,112542.58,False,True
2,502,0,42,8,159660.80,3,1,0,113931.57,False,False
3,699,0,39,1,0.00,2,0,0,93826.63,False,False
4,850,0,43,2,125510.82,1,1,1,79084.10,False,True


In [21]:
from sklearn.preprocessing import StandardScaler

In [22]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=0,stratify=y)

In [24]:
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test= scaler.transform(X_test)

In [25]:
X_train

array([[-1.24021723, -1.09665089,  0.77986083, ...,  1.64099027,
        -0.57812007, -0.57504086],
       [ 0.75974873,  0.91186722, -0.27382717, ..., -1.55587522,
         1.72974448, -0.57504086],
       [-1.72725557, -1.09665089, -0.9443559 , ...,  1.1038111 ,
        -0.57812007, -0.57504086],
       ...,
       [-0.51484098,  0.91186722,  0.87565065, ..., -1.01507508,
         1.72974448, -0.57504086],
       [ 0.73902369, -1.09665089, -0.36961699, ..., -1.47887193,
        -0.57812007, -0.57504086],
       [ 0.95663657,  0.91186722, -1.32751517, ...,  0.50945854,
        -0.57812007,  1.73900686]], shape=(8000, 11))

## Build ANN
• First Layer (Input + Hidden)
– neurons = number of features (11)
– activation = ReLU
• Second Layer
– 128 neurons → more learning power
• Output Layer
– 1 neuron (binary classification)
– sigmoid → gives probability

In [26]:
model=Sequential()
model.add(Dense(X.shape[1],activation='relu',input_dim=X.shape[1]))
model.add(Dense(128,activation='relu'))
model.add(Dense(1,activation='sigmoid'))

/Users/laleshkumar/Python_course/.venv/lib/python3.13/site-packages/keras/src/layers/core/dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [27]:
X.shape[1]

11

• optimizer = Adam → updates weights
• loss = binary_crossentropy → for 0/1 output

In [28]:
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [29]:
model.fit(X_train,y_train.to_numpy(),batch_size=10,epochs=10,verbose=1)

Epoch 1/10
800/800 ━━━━━━━━━━━━━━━━━━━━ 1s 421us/step - accuracy: 0.8095 - loss: 0.4462
Epoch 2/10
800/800 ━━━━━━━━━━━━━━━━━━━━ 0s 410us/step - accuracy: 0.8372 - loss: 0.3974
Epoch 3/10
800/800 ━━━━━━━━━━━━━━━━━━━━ 0s 412us/step - accuracy: 0.8540 - loss: 0.3623
Epoch 4/10
800/800 ━━━━━━━━━━━━━━━━━━━━ 0s 400us/step - accuracy: 0.8606 - loss: 0.3494
Epoch 5/10
800/800 ━━━━━━━━━━━━━━━━━━━━ 0s 544us/step - accuracy: 0.8597 - loss: 0.3440
Epoch 6/10
800/800 ━━━━━━━━━━━━━━━━━━━━ 0s 399us/step - accuracy: 0.8616 - loss: 0.3398
Epoch 7/10
800/800 ━━━━━━━━━━━━━━━━━━━━ 0s 438us/step - accuracy: 0.8631 - loss: 0.3377
Epoch 8/10
800/800 ━━━━━━━━━━━━━━━━━━━━ 0s 400us/step - accuracy: 0.8639 - loss: 0.3345
Epoch 9/10
800/800 ━━━━━━━━━━━━━━━━━━━━ 0s 419us/step - accuracy: 0.8631 - loss: 0.3330
Epoch 10/10
800/800 ━━━━━━━━━━━━━━━━━━━━ 0s 448us/step - accuracy: 0.8631 - loss: 0.3319


In [42]:
y_pred = model.predict(X_test)

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 373us/step


In [43]:
y_pred

array([[0.18276347],
       [0.14273897],
       [0.02968303],
       ...,
       [0.03613239],
       [0.9999863 ],
       [0.05879872]], shape=(2000, 1), dtype=float32)

In [44]:
y_test

1344    1
8167    0
4747    0
5004    1
3124    1
       ..
9107    0
8249    0
8337    0
6279    1
412     0
Name: Exited, Length: 2000, dtype: int64

In [45]:
model.evaluate(X_test,y_test.to_numpy())

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 546us/step - accuracy: 0.8525 - loss: 0.3472


[0.34720370173454285, 0.8525000214576721]

In [46]:
from sklearn.metrics import confusion_matrix, accuracy_score

In [49]:
y_pred_binary = (y_pred > 0.5).astype(int).flatten()
confusion_matrix(y_test, y_pred_binary)

array([[1511,   82],
       [ 213,  194]])

In [51]:
accuracy_score(y_test, y_pred_binary)

0.8525